(use-package prettier
  :ensure t)

(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode))
  :init (setq markdown-command "/usr/local/bin/multimarkdown"))

(use-package lsp-dart
  :ensure t
  :hook (dart-mode . lsp))

(setq treesit-language-source-alist
      '((ruby "https://github.com/tree-sitter/tree-sitter-ruby")))

(setq major-mode-remap-alist
      '((ruby-mode . ruby-ts-mode)))
;	(js2-mode . js-ts-mode)
;	(typescript-mode . typescript-ts-mode)
;	(json-mode . json-ts-mode)
;	(css-mode . css-ts-mode)
;	(yaml-mode . yaml-ts-mode)
;	(dart-mode . dart-ts-mode)))

;(use-package robe
  ;:ensure t
  ;:init 
  ;(add-hook 'ruby-mode-hook 'robe-mode)
  ;(add-hook 'ruby-ts-mode-hook 'robe-mode))

(with-eval-after-load 'eglot
 (add-to-list 'eglot-server-programs '((ruby-mode ruby-ts-mode) "ruby-lsp")))

;; As-generated by Claude AI and not tested, so use at your own risk!
(defun insert-jekyll-post-link (filename link-text)
  (interactive
   (list
    (let ((posts-dir (expand-file-name "_posts" (locate-dominating-file default-directory "_posts"))))
      (if (and (eq major-mode 'dired-mode)
               (region-active-p))
          ;; If in dired with active region, use selected filename
          (file-name-sans-extension
           (file-name-nondirectory
            (dired-get-filename)))
        ;; Otherwise prompt with completion
        (let* ((files (and (file-exists-p posts-dir)
                          (directory-files posts-dir nil "^[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}-.*\\.\\(md\\|markdown\\)$")))
               (names (mapcar #'file-name-sans-extension files)))
          (completing-read "Post file: " names nil t))))
    ;; Get link text from region or prompt
    (if (and (not (eq major-mode 'dired-mode))
             (region-active-p))
        (buffer-substring-no-properties (region-beginning) (region-end))
      (read-string "Link text: "))))
  
  ;; Delete region if it was active (in markdown-mode)
  (when (and (not (eq major-mode 'dired-mode))
             (region-active-p))
    (delete-region (region-beginning) (region-end)))
  
  ;; Insert the formatted markdown link
  (insert "[" link-text "](" "{% post_url " filename " %}" ")"))

(provide 'lang)
